version: "2"
services:
  cassandra:
    build: ./cassandra
    image: okulik/cassandra
    ports:
     - "127.0.0.1:9042:9042"
     - "127.0.0.1:9160:9160"

  elasticsearch_dev:
    build: ./elasticsearch
    image: okulik/elasticsearch
    ports:
     - "127.0.0.1:9201:9200"
     - "127.0.0.1:9301:9200"
    volumes:
      - "${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  elasticsearch_test:
    image: okulik/elasticsearch
    ports:
     - "127.0.0.1:9200:9200"
     - "127.0.0.1:9300:9200"
    volumes:
     - "${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
