version: "2"
services:
  cassandra:
    build: ./cassandra
    image: okulik/cassandra
    ports:
     - "127.0.0.1:9042:9042"
     - "127.0.0.1:9160:9160"

  elasticsearch_dev:
    build: ./elasticsearch
    image: okulik/elasticsearch
    ports:
     - "127.0.0.1:9201:9201"
     - "127.0.0.1:9301:9301"
    volumes:
      - "${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  elasticsearch_test:
    image: okulik/elasticsearch
    ports:
     - "127.0.0.1:9200:9200"
     - "127.0.0.1:9300:9300"
    volumes:
     - "${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  redis:
    image: redis:alpine
    ports:
     - "127.0.0.1:6379:6379"

  memcached:
    image: memcached:alpine
    ports:
     - "127.0.0.1:11211:11211"

  mysql:
    image: mysql:5
    ports:
     - "127.0.0.1:3306:3306"
    volumes:
     - "${PWD}/mysql/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
     - "/private/tmp:/var/run/mysqld"
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  postgres:
    build: ./postgres
    image: okulik/postgres
    ports:
     - "127.0.0.1:5432:5432"
